md params
cd params

copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\common\src\ConvexHullParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\common\include\ConvexHullParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\RenderMeshAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\SubmeshParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\VertexBufferParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\VertexFormatParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\RenderMeshAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\SubmeshParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\VertexBufferParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\VertexFormatParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferF32x1.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferF32x1.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferF32x2.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferF32x2.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferF32x3.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferF32x3.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferF32x4.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferF32x4.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU8x1.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU8x1.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU8x2.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU8x2.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU8x3.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU8x3.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU8x4.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU8x4.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU16x1.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU16x1.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU16x2.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU16x2.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU16x3.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU16x3.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU16x4.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU16x4.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU32x1.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU32x1.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU32x2.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU32x2.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU32x3.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU32x3.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\include\BufferU32x4.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\framework\src\BufferU32x4.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\basicios\src\ApexBasicIOSAssetParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\basicios\include\ApexBasicIOSAssetParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\src\ClothingActorParamSchema.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\src\ClothingAssetParamSchema.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\src\ClothingGraphicalLodParamSchema.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\src\ClothingMaterialLibraryParamSchema.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\src\ClothingPhysicalMeshParamSchema.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\include\ClothingActorParamSchema.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\include\ClothingAssetParamSchema.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\include\ClothingGraphicalLodParamSchema.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\include\ClothingMaterialLibraryParamSchema.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\clothing\include\ClothingPhysicalMeshParamSchema.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\src\ApexDestructibleActorParamSchema.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\src\DestructibleAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\src\SurfaceTraceParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\src\SurfaceTraceSetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\include\ApexDestructibleActorParamSchema.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\include\DestructibleAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\include\SurfaceTraceParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\destructible\include\SurfaceTraceSetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\ApexEmitterActorParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\ApexEmitterAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\EmitterGeomBoxParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\EmitterGeomExplicitParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\EmitterGeomSphereParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\EmitterGeomSphereShellParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\GroundEmitterActorParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\GroundEmitterAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\ImpactEmitterActorParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\src\ImpactEmitterAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\ApexEmitterActorParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\ApexEmitterAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\EmitterGeomBoxParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\EmitterGeomExplicitParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\EmitterGeomSphereParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\EmitterGeomSphereShellParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\GroundEmitterActorParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\GroundEmitterAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\ImpactEmitterActorParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\emitter\include\ImpactEmitterAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\explosion\src\ApexExplosionAssetParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\explosion\src\ExplosionActorParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\explosion\src\ExplosionEnvParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\explosion\include\ApexExplosionAssetParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\explosion\include\ExplosionActorParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\explosion\include\ExplosionEnvParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\src\FieldBoundaryActorParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\src\FieldBoundaryAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\src\ShapeBoxParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\src\ShapeCapsuleParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\src\ShapeConvexParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\src\ShapeSphereParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\include\FieldBoundaryActorParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\include\FieldBoundaryAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\include\ShapeBoxParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\include\ShapeCapsuleParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\include\ShapeConvexParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\forcefield\include\ShapeSphereParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ColorVsDensityModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ColorVsLifeModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\IofxAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\OrientAlongVelocityModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\RandomRotationModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\RandomScaleModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\RandomSubtextureModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\RotationModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ScaleAlongVelocityModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ScaleVsCameraDistanceModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ScaleVsDensityModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ScaleVsLifeModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\SimpleScaleModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\SubtextureVsLifeModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\src\ViewDirectionSortingModifierParams.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ColorVsDensityModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ColorVsLifeModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\IofxAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\OrientAlongVelocityModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\RandomRotationModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\RandomScaleModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\RandomSubtextureModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\RotationModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ScaleAlongVelocityModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ScaleVsCameraDistanceModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ScaleVsDensityModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ScaleVsLifeModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\SimpleScaleModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\SubtextureVsLifeModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\iofx\include\ViewDirectionSortingModifierParams.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\particles\src\NxFluidIosParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\particles\include\NxFluidIosParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\wind\src\ApexWindAssetParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\wind\src\WindActorParameters.cpp
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\wind\include\ApexWindAssetParameters.h
copy \p4\sw\physx\APEXSDK\1.0\feature\UE3_APEX\module\wind\include\WindActorParameters.h

cd ..
